:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge


:scheduler:
  :schedule:
    mark_abandoned_carts:
      cron: '0 */3 * * *'   # Runs every 3 hours
      class: Carts::MarkAbandonedJob
    remove_abandoned_carts:
      cron: '0 0 * * *'     # Runs daily at midnight
      class: Carts::RemoveAbandonedJob